import './globals.css'
import React from "react";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className="h-full">
      <body className="h-full">
        <main className="min-h-screen">
          {children}
        </main>
      </body>
    </html>
  )
}
